name: Java8fx

on:
  push:
    paths:
      - '.github/workflows/java8fx.yml'

jobs:
  java8fx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016, macOS-latest]
        update: [x, 222, 212, 202, 192]
      fail-fast: false
      max-parallel: 5
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: giltene/setup-java@master
      with:
        java-version: 8.0.${{ matrix.update }}
        java-package: jdk+fx
    - name: java -version
      run: java -version
