name: Java10

on:
  push:
    paths:
      - '*/*/java10.yml'

jobs:
  java10:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2016]
        update: [x, 2, 1, 0]
      fail-fast: false
      max-parallel: 5
    name: JDK 10.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: giltene/setup-java@master
      with:
        java-version: 10.0.${{ matrix.update }}
    - name: java -version
      run: java -version
