name: ShortJava8

on:
  push:
    paths:
      - '.github/workflows/ShortJava8.yml'

jobs:
  java8:
    # internal comment counter: 101
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
        update: [x, 201, 192, 181]
        exclude:
          - os: ubuntu-18.04
            update: 101
      fail-fast: false
      max-parallel: 6
    name: JDK 8.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: giltene/setup-java@master
      with:
        java-version: 8.0.${{ matrix.update }}
    - name: java -version
      run: java -version
